INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES (10001, 'Robert', 'Get AWS Certified', CURRENT_DATE, false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES (10002, 'Robert', 'Get Azure Certified', CURRENT_DATE, false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES (10003, 'Robert', 'Get GCP Certified', CURRENT_DATE, false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES (10004, 'Robert', 'Learn DevOps', CURRENT_DATE, false);




